################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\BearSSLHelpers.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\CertStoreBearSSL.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFi.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiGeneric.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiMulti.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiScan.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClient.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClientSecureBearSSL.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServer.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServerSecureAxTLS.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServerSecureBearSSL.cpp \
C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiUdp.cpp 

LINK_OBJ += \
.\libraries\ESP8266WiFi\src\BearSSLHelpers.cpp.o \
.\libraries\ESP8266WiFi\src\CertStoreBearSSL.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFi.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFiGeneric.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFiMulti.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp.o \
.\libraries\ESP8266WiFi\src\ESP8266WiFiScan.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiClient.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiClientSecureBearSSL.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiServer.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiServerSecureAxTLS.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiServerSecureBearSSL.cpp.o \
.\libraries\ESP8266WiFi\src\WiFiUdp.cpp.o 

CPP_DEPS += \
.\libraries\ESP8266WiFi\src\BearSSLHelpers.cpp.d \
.\libraries\ESP8266WiFi\src\CertStoreBearSSL.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFi.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFiGeneric.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFiMulti.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp.d \
.\libraries\ESP8266WiFi\src\ESP8266WiFiScan.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiClient.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiClientSecureBearSSL.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiServer.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiServerSecureAxTLS.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiServerSecureBearSSL.cpp.d \
.\libraries\ESP8266WiFi\src\WiFiUdp.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
libraries\ESP8266WiFi\src\BearSSLHelpers.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\BearSSLHelpers.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\CertStoreBearSSL.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\CertStoreBearSSL.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFi.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFi.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiAP.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFiGeneric.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiGeneric.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFiMulti.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiMulti.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\ESP8266WiFiScan.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\ESP8266WiFiScan.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiClient.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClient.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClientSecureAxTLS.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiClientSecureBearSSL.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiClientSecureBearSSL.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiServer.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServer.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiServerSecureAxTLS.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServerSecureAxTLS.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiServerSecureBearSSL.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiServerSecureBearSSL.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '

libraries\ESP8266WiFi\src\WiFiUdp.cpp.o: C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src\WiFiUdp.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/lwip2/include" "-IC:\eclipse\sloeber\/arduinoPlugin/packages/esp8266/hardware/esp8266/2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-ID:/Projects/Arduino/sloeber-workspace-aurora/AuroraServerWebRest/Release/core" -c -Wall -Wextra  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536   -DARDUINO=10802 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="\"ESP8266_WEMOS_D1MINI\""   -DESP8266   -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\variants\d1_mini" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\ArduinoJson\6.2.3-beta\src" -I"D:\Projects\Arduino\sloeber-workspace-aurora\ArduinoThread" -I"D:\Projects\Arduino\sloeber-workspace-aurora\Aurora_communication_protocol" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\DNSServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WebServer\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\ESP8266WiFi\src" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\NTPClient\3.1.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD\src" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SoftwareSerial" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\SPI" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\Time\1.5.0" -I"C:\eclipse\sloeber\arduinoPlugin\packages\esp8266\hardware\esp8266\2.4.2\libraries\Wire" -I"C:\eclipse\sloeber\arduinoPlugin\libraries\WiFiManager\0.14.0" -I"D:\Projects\Arduino\sloeber-workspace-lib\EMailSender" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -D__IN_ECLIPSE__=1 -x c++ "$<"  -o  "$@"
	@echo 'Finished building: $<'
	@echo ' '


